name: APWorld Fuzzer Action
description: Fuzz your custom APWorlds against Archipelago, in CI
author: dish

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: check-circle
  color: purple

# Define your inputs here.
inputs:
  world:
    description: The world to fuzz
    required: true
  num_gens:
    description: The number of fuzzer runs to do.
    required: false
    default: '100'

# Define your outputs here.
outputs:
  results:
    description: The fuzzer results

runs:
  using: node20
  main: dist/index.js
